# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 79aa2c184380ed2473d737d4682571f9cfd3e873e6f160146dffd375024022aad1d4fb83fbb3f9ed571e0fb273637f07e72bcd0dc0d0f2f72cf188361d7ebfe9

test:
  secret_key_base: 4e9ab8a058305a54c9164c5c3bc54bc5096552eb05e4e98f9abc156a06615fbd1c6aa633a48546fb74dbce3293504fc672e21cb882279ef9b581c31b84311f5c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
